//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing.OrderQueryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderQueryServiceReference.IOrderQueryService")]
    public interface IOrderQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Order/All", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Order/AllResponse")]
        OrderProcessingDomain.Order[] All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Order/Count", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Order/CountResponse")]
        long Count();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Order/First", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Order/FirstResponse")]
        OrderProcessingDomain.Order First();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOrderQueryServiceChannel : OrderProcessing.OrderQueryServiceReference.IOrderQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrderQueryServiceClient : System.ServiceModel.ClientBase<OrderProcessing.OrderQueryServiceReference.IOrderQueryService>, OrderProcessing.OrderQueryServiceReference.IOrderQueryService {
        
        public OrderQueryServiceClient() {
        }
        
        public OrderQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OrderProcessingDomain.Order[] All() {
            return base.Channel.All();
        }
        
        public long Count() {
            return base.Channel.Count();
        }
        
        public OrderProcessingDomain.Order First() {
            return base.Channel.First();
        }
    }
}
