//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStatus")]
    public interface IStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetAllOrders", ReplyAction="http://tempuri.org/IStatus/GetAllOrdersResponse")]
        OrderProcessingDomain.Order[] GetAllOrders();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStatusChannel : OrderProcessing.Tests.ServiceReference1.IStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StatusClient : System.ServiceModel.ClientBase<OrderProcessing.Tests.ServiceReference1.IStatus>, OrderProcessing.Tests.ServiceReference1.IStatus {
        
        public StatusClient() {
        }
        
        public StatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OrderProcessingDomain.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
    }
}
