//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing.OrderStatusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderStatusService.IStatus")]
    public interface IStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetAllOrders", ReplyAction="http://tempuri.org/IStatus/GetAllOrdersResponse")]
        OrderProcessingDomain.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStatus/GetAllOrders", ReplyAction="http://tempuri.org/IStatus/GetAllOrdersResponse")]
        System.IAsyncResult BeginGetAllOrders(System.AsyncCallback callback, object asyncState);
        
        OrderProcessingDomain.Order[] EndGetAllOrders(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStatusChannel : OrderProcessing.OrderStatusService.IStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetAllOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public OrderProcessingDomain.Order[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((OrderProcessingDomain.Order[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StatusClient : System.ServiceModel.ClientBase<OrderProcessing.OrderStatusService.IStatus>, OrderProcessing.OrderStatusService.IStatus {
        
        private BeginOperationDelegate onBeginGetAllOrdersDelegate;
        
        private EndOperationDelegate onEndGetAllOrdersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllOrdersCompletedDelegate;
        
        public StatusClient() {
        }
        
        public StatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllOrdersCompletedEventArgs> GetAllOrdersCompleted;
        
        public OrderProcessingDomain.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllOrders(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllOrders(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public OrderProcessingDomain.Order[] EndGetAllOrders(System.IAsyncResult result) {
            return base.Channel.EndGetAllOrders(result);
        }
        
        private System.IAsyncResult OnBeginGetAllOrders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllOrders(callback, asyncState);
        }
        
        private object[] OnEndGetAllOrders(System.IAsyncResult result) {
            OrderProcessingDomain.Order[] retVal = this.EndGetAllOrders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllOrdersCompleted(object state) {
            if ((this.GetAllOrdersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllOrdersCompleted(this, new GetAllOrdersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllOrdersAsync() {
            this.GetAllOrdersAsync(null);
        }
        
        public void GetAllOrdersAsync(object userState) {
            if ((this.onBeginGetAllOrdersDelegate == null)) {
                this.onBeginGetAllOrdersDelegate = new BeginOperationDelegate(this.OnBeginGetAllOrders);
            }
            if ((this.onEndGetAllOrdersDelegate == null)) {
                this.onEndGetAllOrdersDelegate = new EndOperationDelegate(this.OnEndGetAllOrders);
            }
            if ((this.onGetAllOrdersCompletedDelegate == null)) {
                this.onGetAllOrdersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllOrdersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllOrdersDelegate, null, this.onEndGetAllOrdersDelegate, this.onGetAllOrdersCompletedDelegate, userState);
        }
    }
}
