//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing.CustomerQueryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerQueryServiceReference.ICustomerQueryService")]
    public interface ICustomerQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Customer/All", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/AllResponse")]
        OrderProcessingDomain.Customer[] All();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQueryServiceBaseOf_Customer/All", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/AllResponse")]
        System.IAsyncResult BeginAll(System.AsyncCallback callback, object asyncState);
        
        OrderProcessingDomain.Customer[] EndAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Customer/Count", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/CountResponse")]
        long Count();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQueryServiceBaseOf_Customer/Count", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/CountResponse")]
        System.IAsyncResult BeginCount(System.AsyncCallback callback, object asyncState);
        
        long EndCount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceBaseOf_Customer/First", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/FirstResponse")]
        OrderProcessingDomain.Customer First();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQueryServiceBaseOf_Customer/First", ReplyAction="http://tempuri.org/IQueryServiceBaseOf_Customer/FirstResponse")]
        System.IAsyncResult BeginFirst(System.AsyncCallback callback, object asyncState);
        
        OrderProcessingDomain.Customer EndFirst(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICustomerQueryServiceChannel : OrderProcessing.CustomerQueryServiceReference.ICustomerQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public OrderProcessingDomain.Customer[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((OrderProcessingDomain.Customer[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FirstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FirstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public OrderProcessingDomain.Customer Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((OrderProcessingDomain.Customer)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CustomerQueryServiceClient : System.ServiceModel.ClientBase<OrderProcessing.CustomerQueryServiceReference.ICustomerQueryService>, OrderProcessing.CustomerQueryServiceReference.ICustomerQueryService {
        
        private BeginOperationDelegate onBeginAllDelegate;
        
        private EndOperationDelegate onEndAllDelegate;
        
        private System.Threading.SendOrPostCallback onAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginCountDelegate;
        
        private EndOperationDelegate onEndCountDelegate;
        
        private System.Threading.SendOrPostCallback onCountCompletedDelegate;
        
        private BeginOperationDelegate onBeginFirstDelegate;
        
        private EndOperationDelegate onEndFirstDelegate;
        
        private System.Threading.SendOrPostCallback onFirstCompletedDelegate;
        
        public CustomerQueryServiceClient() {
        }
        
        public CustomerQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AllCompletedEventArgs> AllCompleted;
        
        public event System.EventHandler<CountCompletedEventArgs> CountCompleted;
        
        public event System.EventHandler<FirstCompletedEventArgs> FirstCompleted;
        
        public OrderProcessingDomain.Customer[] All() {
            return base.Channel.All();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public OrderProcessingDomain.Customer[] EndAll(System.IAsyncResult result) {
            return base.Channel.EndAll(result);
        }
        
        private System.IAsyncResult OnBeginAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAll(callback, asyncState);
        }
        
        private object[] OnEndAll(System.IAsyncResult result) {
            OrderProcessingDomain.Customer[] retVal = this.EndAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAllCompleted(object state) {
            if ((this.AllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AllCompleted(this, new AllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AllAsync() {
            this.AllAsync(null);
        }
        
        public void AllAsync(object userState) {
            if ((this.onBeginAllDelegate == null)) {
                this.onBeginAllDelegate = new BeginOperationDelegate(this.OnBeginAll);
            }
            if ((this.onEndAllDelegate == null)) {
                this.onEndAllDelegate = new EndOperationDelegate(this.OnEndAll);
            }
            if ((this.onAllCompletedDelegate == null)) {
                this.onAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAllCompleted);
            }
            base.InvokeAsync(this.onBeginAllDelegate, null, this.onEndAllDelegate, this.onAllCompletedDelegate, userState);
        }
        
        public long Count() {
            return base.Channel.Count();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCount(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCount(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public long EndCount(System.IAsyncResult result) {
            return base.Channel.EndCount(result);
        }
        
        private System.IAsyncResult OnBeginCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginCount(callback, asyncState);
        }
        
        private object[] OnEndCount(System.IAsyncResult result) {
            long retVal = this.EndCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCountCompleted(object state) {
            if ((this.CountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CountCompleted(this, new CountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CountAsync() {
            this.CountAsync(null);
        }
        
        public void CountAsync(object userState) {
            if ((this.onBeginCountDelegate == null)) {
                this.onBeginCountDelegate = new BeginOperationDelegate(this.OnBeginCount);
            }
            if ((this.onEndCountDelegate == null)) {
                this.onEndCountDelegate = new EndOperationDelegate(this.OnEndCount);
            }
            if ((this.onCountCompletedDelegate == null)) {
                this.onCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCountCompleted);
            }
            base.InvokeAsync(this.onBeginCountDelegate, null, this.onEndCountDelegate, this.onCountCompletedDelegate, userState);
        }
        
        public OrderProcessingDomain.Customer First() {
            return base.Channel.First();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFirst(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFirst(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public OrderProcessingDomain.Customer EndFirst(System.IAsyncResult result) {
            return base.Channel.EndFirst(result);
        }
        
        private System.IAsyncResult OnBeginFirst(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginFirst(callback, asyncState);
        }
        
        private object[] OnEndFirst(System.IAsyncResult result) {
            OrderProcessingDomain.Customer retVal = this.EndFirst(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFirstCompleted(object state) {
            if ((this.FirstCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FirstCompleted(this, new FirstCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FirstAsync() {
            this.FirstAsync(null);
        }
        
        public void FirstAsync(object userState) {
            if ((this.onBeginFirstDelegate == null)) {
                this.onBeginFirstDelegate = new BeginOperationDelegate(this.OnBeginFirst);
            }
            if ((this.onEndFirstDelegate == null)) {
                this.onEndFirstDelegate = new EndOperationDelegate(this.OnEndFirst);
            }
            if ((this.onFirstCompletedDelegate == null)) {
                this.onFirstCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFirstCompleted);
            }
            base.InvokeAsync(this.onBeginFirstDelegate, null, this.onEndFirstDelegate, this.onFirstCompletedDelegate, userState);
        }
    }
}
