//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOrders")]
    public interface IOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/AddOrder", ReplyAction="http://tempuri.org/IOrders/AddOrderResponse")]
        void AddOrder(OrderProcessingDomain.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/DeleteOrder", ReplyAction="http://tempuri.org/IOrders/DeleteOrderResponse")]
        void DeleteOrder(OrderProcessingDomain.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetAllOrders", ReplyAction="http://tempuri.org/IOrders/GetAllOrdersResponse")]
        OrderProcessingDomain.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrderCount", ReplyAction="http://tempuri.org/IOrders/GetOrderCountResponse")]
        int GetOrderCount();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOrdersChannel : OrderProcessing.ServiceReference1.IOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrdersClient : System.ServiceModel.ClientBase<OrderProcessing.ServiceReference1.IOrders>, OrderProcessing.ServiceReference1.IOrders {
        
        public OrdersClient() {
        }
        
        public OrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddOrder(OrderProcessingDomain.Order order) {
            base.Channel.AddOrder(order);
        }
        
        public void DeleteOrder(OrderProcessingDomain.Order order) {
            base.Channel.DeleteOrder(order);
        }
        
        public OrderProcessingDomain.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public int GetOrderCount() {
            return base.Channel.GetOrderCount();
        }
    }
}
